# Generated by Django 4.2.1 on 2024-01-02 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0010_uploadfiles_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="slug",
            field=models.SlugField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Минимум 5 символов"
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, message="Максимум 100 символов"
                    ),
                ],
                verbose_name="Slug",
            ),
        ),
    ]
