# Generated by Django 4.2.1 on 2024-03-03 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("women", "0011_women_photo_alter_women_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="autor",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="women.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="husband",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wuman",
                to="women.husband",
                verbose_name="Муж",
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="slug",
            field=models.SlugField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Минимум 5 символов"
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, message="Максимум 100 символов"
                    ),
                ],
                verbose_name="Slug",
            ),
        ),
    ]
